import NavBar from '../components/NavBar'
import Head from 'next/head'
import Main from '@/components/layouts/Main'
import Header from '../components/layouts/Header'

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Home - Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/youtube-svgrepo-com.svg" />
      </Head>
      <Main>
        <Header />
      </Main>
    </div>
  )
}
