import NavBar from '../components/NavBar'
import Head from 'next/head'
import Main from '@/components/layouts/Main'
import Header from '../components/layouts/Header'
import { useEffect } from 'react'

export default function Home({ AllVideo }) {
  return (
    <div className='relative'>
      <Head>
        <title>Home - Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/youtube-svgrepo-com.svg" />
      </Head>
      <Main>
        <Header AllVideo={AllVideo} />
      </Main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://rasmlink.ir/api-v1/youtube_videos`);
  const AllVideo = await res.json();

  if (!AllVideo) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      AllVideo,
    },
  }
}