import NavBar from '@/components/NavBar'
import Head from 'next/head'
import Header from '@/components/layouts/Header'
import Sidebar from '@/components/layouts/Sidebar'
import Main from '@/components/layouts/Main'

export default function Home() {
  return (
    <div className='relative'>
      <Head>
        <title>Home - Youtube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/youtube-svgrepo-com.svg" />
      </Head>
      <Main>
        <Header />
      </Main>
    </div>
  )
}
